CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL
);

CREATE TABLE Books (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Title NVARCHAR(255) NOT NULL,
    Author NVARCHAR(255) NOT NULL,
    IsBorrowed BIT NOT NULL
);

CREATE TABLE Events (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Timestamp DATETIME NOT NULL,
    Description NVARCHAR(MAX),
    UserId UNIQUEIDENTIFIER NOT NULL,
    BookId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (BookId) REFERENCES Books(Id)
);
